# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=6
group=com.mars.laserbridges
java_version=25
deimos_version=2.7
# Common
mod_name=Laser Bridges
mod_author=Mars
mod_id=laserbridges
license=MIT
homepage=https://www.curseforge.com/minecraft/mc-mods/laser-bridges-doors
description=Adds laser sources that create laser platforms and doors when powered
minecraft_version=26.3
minecraft_version_range=[26.3, 27)
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# Fabric
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
modmenu_version=21.0.0-beta.1
# Forge
forge_version=66.0.0
forge_loader_version_range=[66,)
# NeoForge
neoforge_version=26.3.0.1-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.3-1
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
